version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
        environment:
          NSQ_SERVER_PORT_4150_TCP_ADDR: 127.0.0.1
          NSQ_SERVER_PORT_4150_TCP_PORT: 4150
      - image: nsqio/nsq
      command: /nsqlookupd
      - image: nsqio/nsq
      command: /nsqd --lookupd-tcp-address=nsqlookupd:4160


    working_directory: ~/winston-nsq-transport

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
